INCDIR = ../..
LIBDIR = ../../fungus_booster/gcc/lib

all:
	g++ -O3 -s --std=c++0x test0.cpp -I${INCDIR} -L${LIBDIR} -lfungus_booster -lenet -pthread -o ./test0
	g++ -O3 -s --std=c++0x test1.cpp -I${INCDIR} -L${LIBDIR} -lfungus_booster -lenet -pthread -o ./test1
	g++ -O3 -s --std=c++0x test2.cpp -I${INCDIR} -L${LIBDIR} -lfungus_booster -lenet -pthread -o ./test2
	g++ -O3 -s --std=c++0x test3.cpp -I${INCDIR} -L${LIBDIR} -lfungus_booster -lenet -pthread -o ./test3

